"""Este módulo contem todas as strings constantes que serão usadas pelo programa"""

OFF = 'D'
PV = 'PV'
LOAD = 'LOAD'
VOLTAGE_LEVEL = 'VOLTAGE_LEVEL'
SUB = 'SUB'
NAME = 'NAME'
AREA = 'AREA'
BUS_TYPE = 'BUS_TYPE'
EDGE_TYPE = 'EDGE_TYPE'
DLINE = 'DLINE'
XFMR = 'XFMR'
TEMPORARY_FAILURE_RATE = "TEMPORARY_FAILURE_RATE"
PERMANENT_FAILURE_RATE = "PERMANENT_FAILURE_RATE"
REPLACEMENT_TIME = "REPLACEMENT_TIME"
REPAIR_TIME = "REPAIR_TIME"
LOAD_TRANSFER_TIME = 1.5
LOAD_TRANSFER = 0
FAILURE = "Failure"
PROP = "Característica"
ORDER = 'Order'
UT = 'Unavailability'
SAIDI = 'SAIDI'